---
printWidth: 80
tabWidth: 4
useTabs: true
semi: false
singleQuote: true
quoteProps: consistent
jsxSingleQuote: true
trailingComma: es5
bracketSpacing: true
bracketSameLine: true
arrowParens: always
htmlWhitespaceSensitivity: strict
vueIndentScriptAndStyle: false
singleAttributePerLine: true
